### PR TITLE
Unbundle cfitsio

### PR DESCRIPTION
**Pull request by jhunkeler**
:zap:

### CODE REVIEW

**Comment by pllim** [comment]
`+38 −221,894`

I like this! :+1: :+1: :+1:

**Comment by stscicrawford** [comment]
Thanks for the update!

For completeness, can a note be added about this in:  https://github.com/spacetelescope/hstcal/blob/master/INSTALL

**Comment by jhunkeler** [comment]
@stscicrawford 
- `INSTALL` and `README` files have been revamped, rewritten, and converted to Markdown.
- The `LICENSE` file has been renamed to `LICENSE.txt` for the sake of consistency across our projects, and the copyright year has been bumped.

**Comment by jamienoss** [comment]
In conjunction with https://github.com/astroconda/astroconda-dev/pull/122

**Pull request merged**
