### PR TITLE
Unguarded IF in wf32d/do2d.c

### LINKED ISSUE #148: Unguarded IF in wf32d/do2d.c
The following ``if`` is unguarded ([source here](https://github.com/spacetelescope/hstcal/blob/master/pkg/wfc3/calwf3/wf32d/do2d.c#L282-L284)):

```c
if (extver == 1 && !OmitStep (wf32d->flatcorr))
	    if (flatHistory (wf32d, x.globalhdr))
		return (status);
```

It should probably read:

```c
if (extver == 1 && !OmitStep (wf32d->flatcorr))
{
     if (flatHistory (wf32d, x.globalhdr))
		return (status);
 }
```

### PR DESCRIPTION
**Pull request by jamienoss**
fixes #148

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
@sosey can you quickly look at this, please. It should take only a second or two to approve. Thanks.

**Comment by sosey** [comment]
I'm fine with adding brackets there. Technically, this should not be merged to master or delivered with 2017.2a because HSTDP is only accepting changes to ACS with that delivery. @stsci-hack can approve if he wants to do otherwise.

**Comment by jamienoss** [comment]
Why shouldn't this be merged into master?

**Comment by sosey** [comment]
@jhunkeler isn't cherry picking commits for the builds.  If @stsci-hack has decided to change our flow then it should be made known. Otherwise save this pr until after 2017.2a is approved and then merge it.

**Comment by jamienoss** [comment]
We completely changed the way we do releases. There is no longer a need for a code freeze, such as you describe. The branches [candidate-1.2.0](https://github.com/spacetelescope/hstcal/tree/candidate-1.2.0) & [candidate-1.3.0](https://github.com/spacetelescope/hstcal/tree/candidate-1.3.0) were added to handle all code going into 2017.2 & 2017.2a respectively. PRs are opened against these branches and then merged. These branches are then periodically upmerged until they reach master. Master is now pure dev, detached from any release, as it should be. When the time comes that the work diverges further, the next candidate branch will be created to absorb all work for the next release whilst allowing other changes to still be merged.

**Comment by pllim** [comment]
Re: The way we do release -- I want to chime in that I have a difficult time getting used to this new way HSTCAL is branching release candidates. It is a completely different workflow than the rest of the stuff we manage. This should be brought up in a proper HST pipeline software meeting away from this issue comments.

**Comment by sosey** [comment]
I agree with @pllim. Additionally, this was not discussed with the rest of the devs, nor was the information propagated.

**Comment by jamienoss** [comment]
@sosey & @pllim I'm just composing an email to add this to the agenda for the next meeting- going out to SCSB. As far as I was aware, it had been propagated. I was not aware that it had not been so to all those related to hstcal work.

**Comment by jamienoss** [comment]
@stsci-hack Awesome, thanks, and copy that.

**Pull request merged**
