### PR TITLE
changing empty strings to NULLs in fits_write_record. Keyword comment…

### PR DESCRIPTION
**Pull request by SaraOgaz**
…s were not being populated

Resolves issue #77.

### CODE REVIEW

**Comment by SaraOgaz** [comment]
from @philhodge 
"I don't remember anything about this, but it's worth replacing "" with NULL in putHeader to see if that makes a difference.  I would expect cfitsio to populate the comment portion for a reserved keyword, so I would guess that specifying "" instead of NULL was just an oversight.  It looks as if NULL was used for every call to fits_update_key outside of putHeader."

**Comment by SaraOgaz** [comment]
Example FITSDiff report for acs image (but similar for all)

 fitsdiff: 1.2.1
 a: old_results/jczgz1ngq_flt.fits
 b: new_results/jczgz1ngq_flt.fits
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

Primary HDU:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 1:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 2:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 3:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 4:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 5:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 6:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

**Comment by pllim** [comment]
If FITSDIFF complains about it, all the tests in the entire HSTCAL might fail because of this change. Since okify is broken, developers will have to manually copy over all new outputs to the "ref" folder as new truths. A one-time thing but still painful.

I see that http://docs.astropy.org/en/stable/io/fits/api/diff.html has "ignore_comments" keyword. @jhunkeler , is this used in pandokia's `compare_files()`?

**Comment by SaraOgaz** [comment]
So @sosey, @pllim, and @jhunkeler, what happens now...?

**Comment by pllim** [comment]
Would be nice to see if the tests actually fail horribly, as predicted, or not.

https://confluence.stsci.edu/pages/viewpage.action?spaceKey=~jhunk&title=Running+Tests

**Comment by sosey** [comment]
tests can "ignore comments" in pdk. Don't accept this PR until I get the wfc3 tests straightened. I've been in solid meetings until just now and have to leave. I will try and get those taken care of before tests kick off tomorrow and we'll accept this PR by itself to make sure it doesn't collide with any other changes.

**Comment by pllim** [comment]
> tests can "ignore comments" in pdk

How? What is the magical incantation?

**Comment by sosey** [comment]
Actually, I don't believe the tests are checking any keyword comments, just the keyword values and data values. In pdk you can set a list of keywords to ignore, this would ignore the value and the comment. You need to set the 'ignorekeys' dict member when you pass the comparison list into ```filecomp.compare_files```

**Comment by pllim** [comment]
On the contrary, I don't think pdk is that smart. It simply reports whatever fitsdiff spits out, so if fitsdiff complains, it might too.

**Comment by sosey** [comment]
fitsdiff will pick up the comment changes, but I believe if you set pdk to ignore certain keys it will pass the test if only those keys showed differences. It's been a while since I looked at this, @vglaidler

**Comment by pllim** [comment]
Yes, I use `ignorekeys` but that ignores the whole keyword, value and comment altogether. What I am asking here is how to only ignore the comment part?

**Comment by sosey** [comment]
That's what I said above, I don't believe you can ignore just the comment.  I originally did comment above ```tests can "ignore comments" in pdk``` but this morning I realized I was thinking of the ignore list which ignores the whole key.

**Comment by philhodge** [comment]
FITSDiff in astropy.io.fits has an `ignore_comments` argument, the value 
of which is "a list of header keywords whose comments should be ignored 
in the comparison" (quoting from the documentation).  I don't know the 
pdk interface for setting `ignore_comments`.

**Comment by pllim** [comment]
Something went very wrong when you rebase...

**Comment by sosey** [comment]
yah - I messed it up somehow, working on it

**Pull request closed without merging**
