### PR TITLE
Initial commit of Travis-CI configuration

### PR DESCRIPTION
**Pull request by jhunkeler**
🎉  (or at least I hope so)

### CODE REVIEW

**Comment by jhunkeler** [comment]
This commit's results:
https://travis-ci.org/jhunkeler/hstcal/builds/178436258

**Comment by sosey** [comment]
basic viability, nice :8ball:

**Comment by pllim** [comment]
Should we include a small 512 subarray test for each CALxxx? Those should be fast to process.

**Comment by jhunkeler** [comment]
As long as it doesn't take longer than the time limits:
https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts

**Comment by sosey** [comment]
I'm don't think it's worth sitting on travis for a data test. Though the science array is small, many of the steps take full frame reference files, which also have to be transferred, and then the test is still just an aliveness check. I think there is also still a concurrency limit for the number of test running per organization. We have the nightly data regression for actual validation which needs to be looked at with each change anyways. I think the compile validation is decent for the pull requests right now to make sure we aren't outright  breaking the nightly dev build. When/If we move regression systems over to something besides Pandokia we'll have more local resources to throw at a full test for each change. In the mean time, coders should continue to run their own data tests during development and not request a pull until they see results they are expecting. I.E., you should minimally make sure the full package compiles, runs, and produces reasonable results, worthwhile to check on the build machines too and preferably against the test suite, before making the pull request to the hstcal master repo. All intermediate developing  should be done using your personal repository.

**Comment by pllim** [comment]
Good point on the ref files.

However, I can't dig out any specific info on concurrent limit per org. Travis website says "fair use" but implies the limit is shared between all open source repos (?). I was just discussing this with Justin last week. So if you know if this limit is explained anywhere, please let me know. Thanks.

**Comment by jhunkeler** [comment]
"Fair Use" to me implies the open source plan is load balanced aggressively, so if we start to abuse cputime, it will start halting/canceling/queuing/deferring our jobs. I think each virtual image (i.e. job) is limited to 4 threads and has a maximum run time of 120 minutes before being dropped.

**Comment by jhunkeler** [comment]
@sosey Do you mind if I merge this? Or do you need me to implement anything else?

**Comment by sosey** [comment]
@jhunkeler oh, sorry, I thought you had. Yes, merge away

**Comment by jhunkeler** [comment]
WILCO :)

**Pull request merged**
