### PR TITLE
Unguarded IF in ACS SUM mainsum.c - missing {}

### LINKED ISSUE #90: Unguarded IF in ACS SUM mainsum.c - missing {}
[The following code](https://github.com/spacetelescope/hstcal/blob/master/pkg/acs/calacs/acssum/mainsum.c#L88-L95)

```
if (output[0] == '\0') {
	    if (MkName (input, "_asn", "_sfl", "", output, ACS_LINE))
		CloseTrlBuf ();
		free (input);
		free (output);
	    WhichError (status);
		exit (ERROR_RETURN);
	}
```

should probably be
```
if (output[0] == '\0') {
	    if (MkName (input, "_asn", "_sfl", "", output, ACS_LINE)) {
		CloseTrlBuf ();
		free (input);
		free (output);
	    WhichError (status);
		exit (ERROR_RETURN);
    }
}
```

### PR DESCRIPTION
**Pull request by jamienoss**
Fixes #90

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
@pllim please review.

**Comment by pllim** [comment]
I disagree with this change. Please see my comment at https://github.com/spacetelescope/hstcal/issues/90#issuecomment-294235461

**Comment by pllim** [comment]
What is the context of re-opening this again? Sorry, I have been jumping between many projects and a little confused.

**Comment by jamienoss** [comment]
I believe that this is the better action to take.

[Your comment from the issue #90](https://github.com/spacetelescope/hstcal/issues/90#issuecomment-297721052):
 > Re: ACSSUM. As long as making it optional does not break existing functionality, do what you want. Thanks!

**Pull request merged**
