### PR TITLE
TST: Add functionality to upload artfifact

### LINKED ISSUE #388: TST: Functionality to upload artifacts as new truth
Workflow:

1. @jdavies-st to push his stuff upstream to `ci-watson` (something that is already working for `jwst`). ~Need to address the issue with matrix in a single Jenkins file.~ Build matrix works.
2. @pllim to accept the changed in `ci-watson`.
3. @pllim to implement that tech on the `hstcal` side.

Proposed deadline by @stscicrawford : "In the next few days"

After this is done, @mdlpstsci can use it to fix RT failures.

### PR DESCRIPTION
**Pull request by pllim**
Fix #388 

p.s. Not sure how to test this without merging. Maybe we should just merge and see what happens. Any ideas , @rendinam and @jhunkeler ?

### CODE REVIEW

**Comment by jdavies-st** [comment]
One could test this by pointing a Jenkins run to this branch.  I can do this if needed.

**Comment by jdavies-st** [comment]
Here's a Jenkins run pointing to this PR.  Ignore the JWST label.  It is running the `hstcal` JenkinsfileRT.

https://boyle.stsci.edu:8081/job/RT/job/JWST-jdavies/64/

**Comment by pllim** [comment]
Thanks, @jdavies-st ! Unfortunately, the tests failed but did not generate anything that was uploaded. Most of the tests had "ERROR" and not "FAILED". 😱 

@jhunkeler and @rendinam , what does the error mean?

**Comment by jdavies-st** [comment]
Well, it looks like `nott` ran out of space and the build didn't complete.  Top Men™ have been dispatched and a new Jenkins build has been kicked off.

https://boyle.stsci.edu:8081/job/RT/job/JWST-jdavies/65/

**Comment by jdavies-st** [comment]
So it looks like the deployment failed.
```
[RHEL-6/release] ======== 9 failed, 297 passed, 7 xfailed, 1 xpassed in 7431.39 seconds =========
[RHEL-6/release] + true
[Pipeline] [RHEL-6/release] }
[Pipeline] [RHEL-6/release] // stage
[Pipeline] [RHEL-6/release] stage
[Pipeline] [RHEL-6/release] { (Artifactory (release))
[Pipeline] [RHEL-6/release] newBuildInfo
[Pipeline] [RHEL-6/release] collectEnv
[Pipeline] [RHEL-6/release] getArtifactoryServer
[Pipeline] [RHEL-6/release] sh
[RHEL-6/release] [JWST-jdavies] Running shell script
[RHEL-6/release] + find /srv/jenkins/workspace/RT/JWST-jdavies/ -type f
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] readFile
[Pipeline] [RHEL-6/release] newBuildInfo
[Pipeline] [RHEL-6/release] artifactoryUpload
[RHEL-6/release] [consumer_0] Deploying artifact: https://bytesalad.stsci.edu/artifactory/scsb-hstcal-results/2018-12-13_jenkins-RT-JWST-jdavies-65_0/test_subarray_j8c103xaq_0/j8c103xaq_flt_ref.fits
[RHEL-6/release] [Thread consumer_0] An exception occurred during execution:
[RHEL-6/release] java.lang.RuntimeException: java.io.IOException: Failed to deploy file. Status code: 403 Response message: Artifactory returned the following errors: 
[RHEL-6/release] User svc_jenkins is not permitted to deploy '2018-12-13_jenkins-RT-JWST-jdavies-65_0/test_subarray_j8c103xaq_0/j8c103xaq_flt_ref.fits' into 'scsb-hstcal-results:2018-12-13_jenkins-RT-JWST-jdavies-65_0/test_subarray_j8c103xaq_0/j8c103xaq_flt_ref.fits'. Status code: 403
[RHEL-6/release] 	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
[RHEL-6/release] 	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
[RHEL-6/release] 	at java.lang.Thread.run(Thread.java:748)
[RHEL-6/release] Caused by: java.io.IOException: Failed to deploy file. Status code: 403 Response message: Artifactory returned the following errors: 
[RHEL-6/release] User svc_jenkins is not permitted to deploy '2018-12-13_jenkins-RT-JWST-jdavies-65_0/test_subarray_j8c103xaq_0/j8c103xaq_flt_ref.fits' into 'scsb-hstcal-results:2018-12-13_jenkins-RT-JWST-jdavies-65_0/test_subarray_j8c103xaq_0/j8c103xaq_flt_ref.fits'. Status code: 403
[RHEL-6/release] 	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:692)
[RHEL-6/release] 	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:374)
[RHEL-6/release] 	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:362)
[RHEL-6/release] 	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
[RHEL-6/release] 	... 2 more
[RHEL-6/release] 
```
@rendinam @jhunkeler any ideas what might be going on?

**Comment by rendinam** [comment]
The deployment failed due to lack of permissions in the target repository by the service account that Jenkins uses to perform deployments. The correct permissions have now been set.

**Comment by pllim** [comment]
Yay, upload works! Thanks for all your help, @jdavies-st . Congratulations, you are now the HSTCAL CI lead. Har har har.

https://bytesalad.stsci.edu/artifactory/webapp/#/artifacts/browse/tree/General/scsb-hstcal-results/2018-12-13_jenkins-RT-JWST-jdavies-66_0

**Comment by pllim** [comment]
Failures are expected. The point of this PR is so that artifacts from the failed runs can be stored on Artifactory. And since the upload has been proven to work, I am merging this.

**Pull request merged**
