### PR TITLE
Sara ogaz comment bug fix

### PR DESCRIPTION
**Pull request by sosey**
This is the cleaner pull request for sara's changes for comparison with the original pull

### CODE REVIEW

**Comment by pllim** [comment]
Close #78

**Comment by sosey** [comment]
okay, Im merging this one so we can get header update checks moving along... we added a double test run this week to help this.  This update should break all fits file comparison tests because the description fields for required header keywords are changing.

**Comment by pllim** [comment]
> This update should break all fits file comparison tests

Argh!

**Comment by sosey** [comment]
That's why we waited for clean tests.....

**Comment by sosey** [comment]
quick hand check of the files looks like they are failing as expected ... we should update the references after the test run finishes today. @pllim The next build is being pulled at 6pm with tests following so be aware of that time for making the update. Here's the schedule until joe returns:

```
0400 - build
1030 - test
1800 - build
1900 - test
```
fitsdiff: 3.4
 a: iaao01k8q_flt_ref.fits
 b: iaao01k8q_flt.fits
 Maximum number of different data values to be reported: 10
 Data comparison level: 0.0

Primary HDU:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword CAL_VER  has different values:
        a> 3.4(28-Sep-2016)
        b> 3.4.1(Apr-10-2017)
     Keyword DATE     has different values:
        a> 2016-09-29
        b> 2017-04-25
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword ORIGIN   has different comments:
        b> FITS file originator

Extension HDU 1:

   Headers contain differences:
     Keyword BITPIX   has different comments:
        b> number of bits per data pixel
     Keyword DATE     has different values:
        a> 2016-09-29
        b> 2017-04-25
     Keyword NAXIS    has different comments:
        b> number of data axes
     Keyword NAXIS1   has different comments:
        b> length of data axis 1
     Keyword NAXIS2   has different comments:
        b> length of data axis 2
     Keyword ORIGIN   has different comments:
        b> FITS file originator

etc ....

**Comment by pllim** [comment]
So, I guess the only time during office hours I can update the truth is 9-10am or 4-5pm. You are running a tight testing ship!

**Comment by sosey** [comment]
well, we were trying to fit in an extra test run that we could see results, make changes and then be able to check again in the evening and make changes before the 4am build.  There's probably no perfect separation for everyone. But, the afternoon test run completes before 3pm usu, and the next tests don't start til 7, so I think you have a little more wiggle room in there.  :)

**Comment by pllim** [comment]
@stscirij , please check STIS tests!

**Comment by stscirij** [comment]
only fits comment changes.  I OKd them.
________________________________

**Comment by sosey** [comment]
wf3 has been okayed as well

**Pull request merged**
