### PR TITLE
CTE improvements

### PR DESCRIPTION
**Pull request by mdlpstsci**
The CTE algorithm has been significantly improved by J. Anderson.  I have only applied a light touch in that I: 
- removed many of the hard-coded values and replaced them with #define or used values already defined in wf3.h,
- made sure Jay's comments were included in the code in appropriate places, 
- marked out-of-date routines as DEPRECATED though they are still resident in the code for reference at this time, and
- fixed location of some ending braces for readability.

### CODE REVIEW

**Comment by pllim** [comment]
I am guessing the 3 failed tests are expected?

Did you do a benchmark comparison? I am just curious if the improvement includes run time or not.

**Comment by mdlpstsci** [comment]
@pllim Yes, I expect the tests to fail as I have not yet upgraded the truth files.  Also, there is a new calibration reference file which must be submitted by the team.  I am testing with this new, locally named reference file and modified raws which use this file.

Jay stated the new algorithm runs much faster than the old.  By my small number statistics, the execution times are approximately 3.5 to 5 times faster in the new algorithm.

**Comment by mdlpstsci** [comment]
Created the calwf3.e executable (Version 3.6.0 Dec-12-2019) on the Linux servers for testing by WFC3 team members.  Emailed WFC3 team members with this information and instructions.

**Comment by catherine-martlin** [comment]
@mdlpstsci - following the tests run by @bjkuhn and Jay and our chat today that also included Sylvia - the WFC3 team is happy with these updates and give the go ahead on the software updates! Thanks!

**Review by stsci-hack — APPROVED** [review]
LGTM.

**Review by stsci-hack — APPROVED** [review]

**Pull request merged**
