### PR TITLE
Update waf to latest version so we can build in Python 3

### LINKED ISSUE #14: waf not compatible with Python 3?
I get this error running `./waf configure --debug` from Anaconda env with Python 3.5.1. :scream: 

```
Checking for 'gcc' (c compiler)          : ok 
Checking for 'gfortran' (fortran compiler) : ok 
Traceback (most recent call last):
  File ".../waflib/Scripting.py", line 93, in waf_entry_point
    run_commands()
  File ".../waflib/Scripting.py", line 145, in run_commands
    run_command(cmd_name)
  File ".../waflib/Scripting.py", line 138, in run_command
    ctx.execute()
  File ".../waflib/Configure.py", line 127, in execute
    super(ConfigurationContext,self).execute()
  File ".../waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File ".../waflib/Context.py", line 127, in recurse
    user_function(self)
  File ".../wscript", line 149, in configure
    conf.check_fortran()
  File ".../waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File ".../waflib/Tools/fc_config.py", line 32, in check_fortran
    self.check_cc(fragment=FC_FRAGMENT,compile_filename='test.f',features='fc fcprogram',msg='Compiling a simple fortran app')
  File ".../waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File ".../waflib/Tools/c_config.py", line 450, in check_cc
    return self.check(*k,**kw)
  File ".../waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File ".../waflib/Tools/c_config.py", line 356, in check
    ret=self.run_c_code(*k,**kw)
  File ".../waflib/Configure.py", line 220, in fun
    return f(*k,**kw)
  File ".../waflib/Tools/c_config.py", line 434, in run_c_code
    bld.compile()
  File ".../waflib/Build.py", line 191, in compile
    self.store()
  File ".../waflib/Utils.py", line 302, in f
    ret=fun(*k,**kw)
  File ".../waflib/Build.py", line 165, in store
    cPickle.dump(data,f)
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'
```

In a different Anaconda environment with Python 2.7.12 on the same machine, it was successful:

```
Checking for 'gcc' (c compiler)          : ok 
Checking for 'gfortran' (fortran compiler) : ok 
Compiling a simple fortran app             : yes 
Checking for OpenMP                        : OpenMP found. 
Checking for sizeof(int)                   : yes 
Using cfitsio                              : local 
Checking for program make                  : /usr/bin/make 
Copying cfitsio                            : done 
Configuring cfitsio                        : done 
Checking for compiler flags -g             : yes 
Checking for compiler flags -O0            : yes 
Checking for compiler flags -Wall          : yes 
'configure' finished successfully (5.457s)
```

### PR DESCRIPTION
**Pull request by pllim**
Status: Got it to build. Checking to see if this changes ACS results.

Fixes #14 .

To update it:

* git clone https://github.com/waf-project/waf.git
* ~~Copy our own `waf_patches/g77.py` to `waflib/Tools/` in the cloned repo.~~
* ~~Add `'g77'` as shown below in `waflib/Tools/compiler_fc.py`~~:

```python
    fc_compiler = {
        ...  
        'linux'  : ['gfortran', 'g95', 'ifort', 'g77' ],
        ...
    }
```

* Run this from top level of the repo:
`./waf-light --zip-type=gz configure build `
* Copy the "waf" executable to our HSTCAL repo to replace the old one.
* Update `wscript`, if necessary.

### CODE REVIEW

**Comment by pllim** [comment]
Currently stuck at:

```
[619/619] Linking build.Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago/pkg/wfc3/calwf3/wf3cte/wf3cte.e
pkg/acs/calacs/lib/libcalacs.a(dophot.c.1.o): In function `doPhot':
dophot.c:(.text+0x15d): undefined reference to `InitPhotPar'
dophot.c:(.text+0x168): undefined reference to `GetPhotTab'
dophot.c:(.text+0x2ea): undefined reference to `FreePhotPar'
collect2: ld returned 1 exit status

Waf: Leaving directory `.../build.Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago'
Build failed
 -> task in 'acs2d.e' failed (exit status 1): 
	{task 139631034037592: cprogram main2d.c.1.o -> acs2d.e}
['/usr/bin/gcc', 'pkg/acs/calacs/acs2d/main2d.c.1.o', '-o/user/lim/ssb/calacs/fork/build.Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago/pkg/acs/calacs/acs2d/acs2d.e', '-Wl,-Bstatic', '-Lpkg/imphttab', '-Lpkg/acs/calacs/lib', '-Lapplib', '-Ltables', '-Lhstio', '-Lcvos', '-limphttab', '-lcalacs', '-lapplib', '-lxtables', '-lhstio', '-lcvos', '-lcfitsio', '-Wl,-Bdynamic', '-L/user/lim/ssb/calacs/fork/build.Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago/lock_cfitsio', '-lm', '-lgomp']
 -> task in 'calacs.e' failed (exit status 1): 
	{task 139631033990960: cprogram acsmain.c.1.o -> calacs.e}
['/usr/bin/gcc', 'pkg/acs/calacs/calacs/acsmain.c.1.o', '-o/.../build.Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago/pkg/acs/calacs/calacs/calacs.e', '-Wl,-Bstatic', '-Lpkg/imphttab', '-Lpkg/acs/calacs/lib', '-Lapplib', '-Ltables', '-Lhstio', '-Lcvos', '-limphttab', '-lcalacs', '-lapplib', '-lxtables', '-lhstio', '-lcvos', '-lcfitsio', '-Wl,-Bdynamic', '-L/user/lim/ssb/calacs/fork/build.Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago/lock_cfitsio', '-lm', '-lgomp']
```

**Comment by jhunkeler** [comment]
@pllim Your modifications worked flawlessly on my end, under OS X anyway! I wonder why it failed for you...


```
% ./configure
Checking for WAF			:  /Users/jhunk/Downloads/hstcal/waf
Setting top to                           : /Users/jhunk/Downloads/hstcal
Setting out to                           : /Users/jhunk/Downloads/hstcal/build.Darwin-15.6.0-x86_64-i386-64bit
Checking for 'clang' (C compiler)        : /usr/bin/clang
Checking for 'gfortran' (Fortran compiler) : /Users/jhunk/.local/bin/gfortran
Compiling a simple fortran app             : self.env.INCLUDES = []
yes
Checking for OpenMP                        : self.env.INCLUDES = ['/Users/jhunk/Downloads/hstcal/include']
OpenMP not found.
Determining Mac OS-X version               : Do not recognize this Mac OS only know 10.5-10.9
Checking for sizeof(int)                   : self.env.INCLUDES = ['/Users/jhunk/Downloads/hstcal/include']
yes
Using cfitsio                              : local
Checking for program 'make'                : /usr/bin/make
Copying cfitsio                            : done
Configuring cfitsio                        : done
Checking for compiler flags -O2            : self.env.INCLUDES = ['/Users/jhunk/Downloads/hstcal/include']
yes
Checking for compiler flags -Wall          : self.env.INCLUDES = ['/Users/jhunk/Downloads/hstcal/include']
yes
Checking for compiler flags -fstack-protector-all : self.env.INCLUDES = ['/Users/jhunk/Downloads/hstcal/include']
yes
'configure' finished successfully (4.317s)
```

^ My `gfortran` is just a symlink back to the binary built with MacPorts; nothing special.

End of build log:

```
make
/Users/jhunk/Downloads/hstcal/waf build
Waf: Entering directory `/Users/jhunk/Downloads/hstcal/build.Darwin-15.6.0-x86_64-i386-64bit'

...

[588/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/lib/libcalstis.a
[589/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/hstio/libhstio.a
[590/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/cvos/libcvos.a
[591/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/applib/libapplib.a
[592/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/lib/libcalacs.a
[593/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/tables/libxtables.a
[594/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs12/cs12.e
[595/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs7/cs7.e
[596/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs11/cs11.e
[597/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs4/cs4.e
[598/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/imphttab/testphot.e
[599/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/imphttab/libimphttab.a
[600/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/hstio/test/test_hstio_resize_hdu
[601/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/hstio/test/test_hstio_resize_hdu2
[602/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/acssum/acssum.e
[603/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs2/cs2.e
[604/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs1/cs1.e
[605/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs0/cs0.e
[606/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/acs2d/acs2d.e
[607/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/calacs/calacs.e
[608/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/acscte/acscte.e
[609/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/acsccd/acsccd.e
[610/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/acs/calacs/acsrej/acsrej.e
[611/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/stis/calstis/cs6/cs6.e
[612/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/lib/libcalwf3.a
[613/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/wf32d/wf32d.e
[614/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/wf3ir/wf3ir.e
[615/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/calwf3/calwf3.e
[616/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/wf3cte/wf3cte.e
[617/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/wf3rej/wf3rej.e
[618/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/wf3ccd/wf3ccd.e
[619/619] Linking build.Darwin-15.6.0-x86_64-i386-64bit/pkg/wfc3/calwf3/wf3sum/wf3sum.e
Waf: Leaving directory `/Users/jhunk/Downloads/hstcal/build.Darwin-15.6.0-x86_64-i386-64bit'
'build' finished successfully (27.578s)
```

**Comment by pllim** [comment]
Thanks for checking, @jhunkeler ! Phil suggested that I look at the full log to make sure the phot codes actually compiled, so I have plans to check that when I get the chance. It appears you used an older commit of this PR. I have since removed the weird print output when you configure, FYI. (It was added in to debug `wscript`.)

**Comment by jhunkeler** [comment]
Hm, there's only 1 commit on this PR though. ;)

**Comment by sosey** [comment]
check the versions on the compilers, osx uses a MUCH more recent one that our linux machines and has caused me issue....see if it compiles cleaner on a newer gcc? 

consider updating this flag in the configure too, I put it in two years ago when we had younger osx around too 

```Determining Mac OS-X version               : Do not recognize this Mac OS only know 10.5-10.9```

**Comment by pllim** [comment]
@jhunkeler , my bad. The other commit is still local only. I'll push it out after I look at the Linux failure.

**Comment by pllim** [comment]
@sosey, here's my configure output on Linux:

```
$ ./waf configure --debug
...
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'gfortran' (Fortran compiler) : /usr/bin/gfortran 
Compiling a simple fortran app             : yes 
Checking for OpenMP                        : OpenMP found. 
Checking for sizeof(int)                   : yes 
Using cfitsio                              : local 
Checking for program 'make'                : /usr/bin/make 
Copying cfitsio                            : done 
Configuring cfitsio                        : done 
Checking for compiler flags -g             : yes 
Checking for compiler flags -O0            : yes 
Checking for compiler flags -Wall          : yes 
'configure' finished successfully (6.759s)

$ /usr/bin/gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ /usr/bin/gfortran --version
GNU Fortran (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
```

**Comment by sosey** [comment]
@pllim my point was the macs are using a much higher version of gcc, both systems are softlinking gfortran back to gcc:

```
bash-3.2$ gfortran --version
GNU Fortran (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
```

additionally, on our macs, gcc is silently calling the clang:

```
bash-3.2$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by pllim** [comment]
There is no specific failure of `phot` stuff compiling further up top, so I have no idea what is going on here. Also, I don't think it's the compiler version because HSTCAL builds successfully with an older version of `waf` (the one that choked on Python 3). I am attaching the full log below for your enjoyment. My next attempt is to remove that `g77` patching to `waf` for Linux and try again.

[zwaf_build_log.txt](https://github.com/spacetelescope/hstcal/files/490268/zwaf_build_log.txt)

Also, what is the proper way to check for Mac version now? I don't use Mac, so I have no idea. The code is in `_determine_mac_osx_fortran_flags()` in the top level `wscript`.

**Comment by jhunkeler** [comment]
@pllim @sosey I tried with `clang-3.4.2` under CentOS 6.8

```
$ clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
```

The failure remained the same.

**Comment by pllim** [comment]
I removed the manual `g77` patching and still get the same failure (log below). So my hypothesis is that the patch is not compatible with this new `waf`.

[zwaf_build_log_2.txt](https://github.com/spacetelescope/hstcal/files/490298/zwaf_build_log_2.txt)

**Comment by jhunkeler** [comment]
I just tried again with Fedora 24 with using both `clang-3.8.0` and `gcc-6.1.1` ... Same error(s)

**Comment by pllim** [comment]
Update: @jhunkeler is going to run this PR with ACS test suite, just to prove that this update does not change science results (I don't see how it can). If it passes, I think we can merge.

**Comment by pllim** [comment]
@sosey , thanks. That was the information I needed. Does cb01dc7 addresses your concern? I have it set such that the OS name is green if that flag is set, or yellow if not. I think it is more informative that way. But I can change the color to just green regardless if you don't like this.

**Comment by pllim** [comment]
@sosey , thanks. Please see 0ce270b

**Comment by pllim** [comment]
@jhunkeler , can we merge this yet?

**Comment by pllim** [comment]
:santa: nodded. Merging!

**Pull request merged**
