### PR TITLE
CTE and  SINK pixel corrections enabled for user subarray images

### PR DESCRIPTION
**Pull request by sosey**
This update enables https://github.com/spacetelescope/hstcal/issues/8 and supersedes https://github.com/spacetelescope/hstcal/pull/5

- Sink pixel detection complete for subarrays
- CTE correction enabled for subarrays with physical overscan
- Some general cleanup of the code
- Some cleanup of top level information files for HSTCAL

### CODE REVIEW

**Comment by pllim** [comment]
By the way, "fixes #8 and closes #5" would automatically close those two PRs when this is merged.

**Comment by sosey** [comment]
@pllim that's the idea, is there a problem with me closing issues?

**Comment by pllim** [comment]
@sosey, no. Github looks for certain words, like "fixes <issue num>" and "closes <issue num>", so I was just inserting those to make sure that really happens as intended.

**Comment by sosey** [comment]
@pllim okay, so what if I didn't want that to happen, maybe I want to update this pull with team fixes before merging, you don't know. Perhaps just let me manage the issues on the package I'm currently working on and trust that I know what I want to be done.

**Comment by pllim** [comment]
Okay, I'll delete the comment above. Just want to make sure. Thanks.

**Pull request merged**
