### PR TITLE
Upgrade waf to 1.9.9

### LINKED ISSUE #86: waf is not compatible with Python 3.6
As evident in our accidental Travis failures and also reported at waf-project/waf#1889. An upgrade to 1.9.9 like #15 should fix it, hopefully.

### PR DESCRIPTION
**Pull request by pllim**
Fix #86 

Needed by #82 to debug actual errors. Otherwise, get `NoneType` exceptions from Python 3.6.

Note that #85 still needs to be addressed because we are not supposed to be using Python 3.6 yet in the first place (see #73) but this PR will future-proof HSTCAL installation.

c/c @jamienoss @sosey @jhunkeler

### CODE REVIEW

**Comment by pllim** [comment]
@jamienoss , I got rid of the `NoneType` errors here. But I don't know what these new errors are.

@sosey , should we go ahead and upgrade `waf` to 1.9.9 outside Jamie's changes anyway?

**Comment by jamienoss** [comment]
@pllim Cool, thanks. It seems that the errors are now genuine - it's complaining about my use of the C99 standard.

**Comment by pllim** [comment]
@jamienoss , you can either push your fixes here (to my branch as a maintainer) or continue in #82. Theoretically, if you fixed your actual errors, the Python 3.6 `NoneType` errors will go away as well, as the latter was triggered by the former.

If you want to work in #82, I'll remove your commit from this PR, and make this a pure `waf` upgrade PR.

**Comment by sosey** [comment]
I think it would be nicer to put the waf in separately

**Comment by pllim** [comment]
@sosey , in that case, would be nice to merge the `waf` only PR in ASAP, so Jamie can rebase and take advantage of it. What do you think?

**Comment by sosey** [comment]
@pllim I'm fine with that

**Comment by pllim** [comment]
Okay. I removed changes from #82 here. Will merge when tests pass.

**Pull request merged**
