### PR TITLE
**DO NOT MERGE** CALACS to use new DARKTIME keyword

### PR DESCRIPTION
**Pull request by pllim**
**Do not merge. Pending approval from ACS Team.**

See https://trac.stsci.edu/ssb/stsci_python/ticket/1167

ACS investigation: https://confluence.stsci.edu/pages/viewpage.action?pageId=73765586

### CODE REVIEW

**Comment by pllim** [comment]
Update: ACS Team confirmed that they are still investigating the accuracy of DARKTIME values and this will **not** be ready by 2017.2.

**Comment by jamienoss** [comment]
@pllim What's the status for this? Is it a 2017.2a (hstcal-1.3.0) or 2017.3 (hstcal-1.4.0) addition (if at all)?

**Comment by pllim** [comment]
No, just leave it alone for now. I'll provide update when available.

**Comment by pllim** [comment]
Update: During ACS meeting on July 5, 2017, it was mentioned that Nathan Miles is still investigating and will provide an update around November 2017.

**Comment by pllim** [comment]
I think we can close this now, @mdlpstsci and @nmiles2718 ?

**Comment by pllim** [comment]
I am re-opening this based on Nathan's response above.

**Comment by stscicrawford** [comment]
Thanks for clarification and re-opening it.

**Comment by pllim** [comment]
I think this has been superseded by something @mdlpstsci did.

**Pull request closed without merging**
