### PR TITLE
Have gcc supersede clang when finding C compiler

### LINKED ISSUE #42: Have GNU supersede clang?
Might it be an idea to have the configure script default to gnu compilers rather than clang?

### PR DESCRIPTION
**Pull request by jamienoss**
Fixes #42 

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
@jhunkeler please take a look and play around, and see what you think. Cheers

**Comment by sosey** [comment]
gcc silently links to the clang on current installs of MacOS, I'm not sure this gets around that issue, have you tested it?

Also, there are no plans to translate hstcal to c++, I think putting the future proofing statements in would be misleading to others looking at the code.

**Comment by jamienoss** [comment]
@sosey Correct, in fact on 10.11 it's even a renamed copy rather than a link. I had tested this and even looked at the waf source - it runs the preprocessor and then searches through the output to determine if it's actually gcc rather than an imposter. @jhunkeler knows more about waf than I do, hence my message to have him look at it to extend any possible further testing etc.

**Comment by jamienoss** [comment]
@sosey done :)
@jhunkeler does this change look ok to you?

**Comment by jhunkeler** [comment]
For the record `/usr/bin/gcc` on OS X is just a link back to `clang`, however I like this because it will automagically discover our real gcc compiler while building under conda instead of exploding.

👍

**Comment by sosey** [comment]
@jhunkeler  yah, I'm down with that. Perhaps we should make a note for repo users that if they are building outside of our conda environment they may experience clang related turbulence?

**Pull request merged**
