### PR TITLE
EXP: Multi arch build

### PR DESCRIPTION
**Pull request by pllim**
@sean-lockwood asked and now I am curious.

### CODE REVIEW

**Comment by sean-lockwood** [comment]
I was able to manually build HSTCAL for ARM32 on my Raspberry Pi 4B (Raspberry Pi OS, Buster; 32-bit OS).
An initial reduction of a STIS dataset gave identical results to MAST.

**Comment by pllim** [comment]
Sean, great! Now we don't need AWS no more. An army of Raspberry Pi probably cheaper. 😉

**Comment by pllim** [comment]
Hmm. How did you install cfitsio there? Apparently there is no conda available for ARM64.

**Comment by sean-lockwood** [comment]
Built from source.  There were some library dependencies I had to track down and "apt install".

**Comment by sean-lockwood** [comment]
And apparently while the 4B is a 64-bit architecture, the OS is still 32-bit for now.  They're testing a 64-bit version...

**Comment by pllim** [comment]
Interesting... You should try to install PyRAF there next while it is still 32-bit.

**Comment by pllim** [comment]
Re: https://github.com/spacetelescope/hstcal/pull/523#issuecomment-690328854

Ouch. Definitely a bug. Do you want to open PR to fix them? We don't support Python 2 anymore.

**Comment by pllim** [comment]
p.s. No idea where that file came from, the git blame makes no sense to me. It wasn't modified for 10 years.

**Comment by pllim** [comment]
So, looks like it is possible to build HSTCAL on all the architectures supported by Travis CI on Linux. You just can't use `conda`. Case closed.

**Comment by pllim** [comment]
p.s. Building it is one thing, making sure the numbers are still correct is another...

**Pull request closed without merging**
