### PR TITLE
Bump ACS version to 9.2.0

### LINKED ISSUE #146: Prep CALACS for 2017.2a delivery
ACS Team has approved the CTE code for delivery this morning during ACS meeting. Now, the following needs to be done to wrap things up:

* Add an entry to `pkg/acs/calacs/Updates` (see "History" and "Dates")
* Updated date stamp in `ACS_CAL_VER` to "28-Apr-2017" to be consistent with "History"
* Tag a new release candidate for 2017.2a -- This is needed for delivery to HSTDP for testing

c/c @jhunkeler @rendinam @stsci-hack

### PR DESCRIPTION
**Pull request by jamienoss**
This updates the following files:

pkg/acs/calacs/Dates
pkg/acs/calacs/History
pkg/acs/calacs/Updates
pkg/acs/calacs/include/acsversion.h

resolves #146

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

**Comment by jamienoss** [comment]
@pllim please review, have I missed something?

**Comment by pllim** [comment]
I thought we discussed about not bumping the version and doing it your way? But even as-is, this looks okay to me. We can worry about tagging RC once you get the final reference file and regression tests sorted out. Thanks! 👍

**Comment by jamienoss** [comment]
But like you said, the instrument team had been testing your sinkcorr code etc which was versioned as 9.1.0, as you pointed out, they may get confussed if the new cte is added as the same version. Your were/are right about not changing history, so I even moved my cte changes to 9.2 rather than 9.1.

In the future, we should not be doing this, pkg version changes should only exist with an actual corresponding release version instead of being orphaned as they have been.

**Comment by pllim** [comment]
Sure. Thanks!

**Comment by pllim** [comment]
@jhunkeler has a `relics` package that does auto-versioning but not sure how to apply that to CALXXX each separately here. But that is a discussion for post-2017.2a.

**Pull request merged**
