### PR TITLE
Basic infrastructure changes needed to support saturation map.

### PR DESCRIPTION
**Pull request by mdlpstsci**
Initial push of infrastructure changes to support the saturation map.  The changes thus far do NOT accommodate binning.

### CODE REVIEW

**Review by stscirij — DISMISSED** [review]
Looks fine as far as I can tell, I made a comment about replacing numbers in the code with defined quantities that describe what they represent, but this is more than a style thing to help readers of the code.  Only for these changes, I wouldn't go through all the code to clean up then numbers. could do a separate ticket for that if you feel it's worth it

**Comment by mdlpstsci** [comment]
Hi,
Thank you for the review.  Of course, you are correct. I cannot merge yet as I am waiting for test data from WFC3, so I can make this change.  I should have done it in the first place.
Best,
M

Michele D. De La Peña
***@***.******@***.***>
Science Calibration Software Branch
Space Telescope Science Institute
Mobile: 520.419.8825
Office: 667.218.6501

From: Robert Jedrzejewski ***@***.***>
Reply-To: spacetelescope/hstcal ***@***.***>
Date: Monday, April 17, 2023 at 10:04 AM
To: spacetelescope/hstcal ***@***.***>
Cc: Michele De La Pena ***@***.***>, Assign ***@***.***>
Subject: Re: [spacetelescope/hstcal] WIP: Basic infrastructure changes needed to support saturation map. (PR #563)


@stscirij approved this pull request.

Looks fine as far as I can tell, I made a comment about replacing numbers in the code with defined quantities that describe what they represent, but this is more than a style thing to help readers of the code

**Review by stscirij — DISMISSED** [review]
Looks good!

**Comment by mdlpstsci** [comment]
Tested with my own test datasets, and more importantly, with datasets provided by WFC3 (1x1: iem354khq, 2x2: ibl999tfqa, 3x3: iacs02tyq, and subarray: if2r02agq.  My results agree with those of WFC3.

**Comment by mdlpstsci** [comment]
Code has already been approved and small change made to a comment.

**Comment by mdlpstsci** [comment]
Resolves Issue #584 #558

**Pull request merged**
