### PR TITLE
Sink Detect sub-array code

### PR DESCRIPTION
**Pull request by brechmos-stsci**
The code changes are primarily for the Sink Detect algorithm to run on sub-array's of data.  This was done by creating an empty full-array in doccd.c, copying in the sub-array, running the original algorithm (sink.c) and then copying out the relevant sub-array DQ.

There is also a very minor bug fix in the sink.c code.

Megan will be reviewing and validating the work.

### CODE REVIEW

**Comment by pllim** [comment]
Would  be nice to list relevant Trac Tickets here for future reference.

Also, just out of curiosity, did you run this through the nightly regression test suite?

c/c @sosey

**Comment by sosey** [comment]
@pllim no, we haven't run this through the suite. This is Craig's first go at working with the pipeline code, and I'm still cleaning out the suite from our move. So I asked him to make the pull request so that I could review the code and try it myself.  When the tests are working correctly,  and we approve the code I'll approve the request and they'll run through the official dev nightly.

**Comment by pllim** [comment]
Okay, just making sure. I am still trying to get used to using GitHub for HSTCAL. :smile: I'll add him to the repo group.

**Comment by sosey** [comment]
@brechmos-stsci  I'm gunna go ahead and close this pull request since the cte request has the sink pixel updates in it as well. We'll do the code review and both updates on that pull, agreed?

**Comment by sosey** [comment]
@brechmos-stsci  no worries - everytime I try and start the code review I get interrupted, so I'm behind on this...

**Pull request closed without merging**
